### ISSUE TITLE
Where is the AndroidManifest?

### ISSUE THREAD

**Issue by b3326023** [reubenkcoutinho/MyoMobileVRApp#1]
Please,Where is the AndroidManifest?
I can't find it......
THX!

**Comment by alt-ctrl-dev** [comment]
Here's a copy of the manifest file i used
[AndroidManifest.xml.txt](https://github.com/reubenkcoutinho/MyoMobileVRApp/files/753399/AndroidManifest.xml.txt)

**Comment by b3326023** [comment]
Thank you!But I still have a question:where should I put this in?In the
Asset directory?


2017年2月6日 07:21，"Reuben K. Coutinho" <notifications@github.com>寫道：

**Comment by alt-ctrl-dev** [comment]
It should be in the Assets\Plugins\Android folder

**Comment by b3326023** [comment]
Ok!Thank you very much!

By Yi-Wei Cheng

2017年2月6日 上午10:15，"Reuben K. Coutinho" <notifications@github.com>寫道：

**Comment by b3326023** [comment]
Excuse me,I have run the app on my phone , and I have give it the
permission,and I have turned on the bluetooth,but while I click "Attach to
adjacent" button and let my Myo Armband to get close to it,the app doesn't
do anything,it cannot connect to Myo.....
I return to read your Instruction:
But I don't understand the first and second steps,
1:add what plugin?
2:I didn't find the folder and the myo.dll
Could you help me?
Thanks very much!
Instructions

   - Add the unity plugin
   - delete myo.dll fron x86_64 folder
   - Add this <https://github.com/reubenkcoutinho/MyoMobileVRApp/issues/1> to
   the AndroidManifest to make it work
   - Build and run


2017-02-06 10:23 GMT+08:00 鄭宜崴 <b3326023a@gmail.com>:

**Comment by alt-ctrl-dev** [comment]
Hi,

use this [plugin](https://github.com/f-strieg/MyoUnityAndroidPlugin) via import-> custom plugin. After you import the file, there will be a x86_64 folder. Check and see if myo.dll exists. if it exists delete the myo.dll file.

**Comment by b3326023** [comment]
Hello,I want to ask another question,why the app doesn't have VR effect?
It is just a normal 3D game😩
Thx!

2017-02-06 11:50 GMT+08:00 Reuben K. Coutinho <notifications@github.com>:

**Comment by alt-ctrl-dev** [comment]
Select the GVRViewerMain prefab in the scene and in the inspector check the VR mode
